export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_INFO_CATEGORY = "GET_INFO_CATEGORY";
export const EDIT_INFO_CATEGORY = "EDIT_INFO_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_VISIBLE_CATEGORY = "SET_VISIBLE_CATEGORY";
